import { lazy, Suspense } from 'react'
import { Activity, ArrowRight, Building2, CheckCircle2, ChevronRight, CircleDot, GraduationCap, HeartHandshake, Layers3, Route, SearchCheck, ShieldCheck, Sparkles, Target, UsersRound } from 'lucide-react'
import { Link } from 'react-router'
import { Logo } from '../components/Logo'

const RelationshipScene = lazy(() => import('../components/RelationshipScene').then((module) => ({ default: module.RelationshipScene })))
const features = [
  { icon: Target, title: 'A pipeline with a pulse', text: 'See what is moving, what is waiting, and who owns the next step without digging through tabs.', action: 'Start with the pipeline' },
  { icon: UsersRound, title: 'Context that stays together', text: 'Keep customer details, notes, activity, and tasks connected from first contact to renewal.', action: 'Keep context together' },
  { icon: Layers3, title: 'A focus queue for today', text: 'Work from deterministic priorities: overdue, due soon, quiet leads, and proposals waiting for a response.', action: 'Build a focus queue' },
]
const domainCards = [
  { icon: Building2, label: 'Agencies & services', text: 'Keep every client, project conversation, renewal, and owner connected.' },
  { icon: HeartHandshake, label: 'Account management', text: 'Turn relationship health into visible follow-ups before accounts go quiet.' },
  { icon: GraduationCap, label: 'Education & recruiting', text: 'Track applicants, partners, and time-sensitive next steps with less chasing.' },
]

export function LandingPage() {
  return <div className="landing">
    <header className="landing-nav"><Logo /><nav aria-label="Landing page sections"><a href="#workflow">Workflow</a><a href="#surface">What it covers</a><a href="#security">Trust</a></nav><div className="landing-actions"><Link className="text-button" to="/login">Sign in</Link><Link className="button button-dark button-small" to="/register">Launch CRM <ArrowRight size={15} /></Link></div></header>
    <main>
      <section className="hero section-wrap"><div className="hero-copy"><div className="eyebrow"><span className="eyebrow-dot" /> Built for small, serious teams</div><h1>Every relationship.<br /><span>Every next step.</span></h1><p className="hero-lede">CRM360 brings customer context, sales momentum, and team follow-through into one clear workspace—so your CRM helps people act, not just report.</p><div className="hero-actions"><Link className="button button-dark" to="/register">Start with CRM360 <ArrowRight size={17} /></Link><a className="button button-quiet" href="#workflow">See how it works <ChevronRight size={17} /></a></div><div className="hero-proof"><span><CheckCircle2 size={15} /> Real workflows</span><span><CheckCircle2 size={15} /> Clear ownership</span><span><CheckCircle2 size={15} /> Honest status</span></div></div><div className="hero-visual" aria-label="Illustrative CRM360 relationship map preview"><Suspense fallback={<div className="relationship-scene-fallback" aria-hidden="true"><b>CRM360</b></div>}><RelationshipScene /></Suspense><div className="hero-stage-label"><Sparkles size={14} /><span>Illustrative preview</span><small>Relationship context and momentum</small></div><div className="floating-card floating-card-top"><span className="mini-avatar accent-avatar">A</span><div><strong>Example account</strong><small>Proposal sent · $18.4k</small></div><span className="signal signal-accent" /></div><div className="floating-card floating-card-bottom"><span className="task-check"><CheckCircle2 size={16} /></span><div><strong>Example next action</strong><small>Follow up on proposal · Today</small></div><span className="signal signal-warning" /></div></div></section>
      <section className="trust-strip section-wrap"><span>One calm layer over your sales motion</span><div><b>LEADS</b><i>→</i><b>FOLLOW-UPS</b><i>→</i><b>CONTEXT</b><i>→</i><b>PROGRESS</b></div></section>
      <section id="workflow" className="section-wrap workflow-section"><div className="section-intro"><span className="eyebrow">The workflow</span><h2>From new lead to next win, without losing the thread.</h2><p>CRM360 is designed around the work your team already does—made visible, connected, and easier to finish.</p></div><div className="workflow-grid"><div className="workflow-rail"><span className="rail-line" /><div className="workflow-step active"><b>01</b><div><strong>Capture</strong><span>Get every new opportunity into one place.</span></div></div><div className="workflow-step"><b>02</b><div><strong>Clarify</strong><span>Assign an owner, stage, and next action.</span></div></div><div className="workflow-step"><b>03</b><div><strong>Follow through</strong><span>Turn conversations into tasks and history.</span></div></div><div className="workflow-step"><b>04</b><div><strong>Convert</strong><span>Move qualified relationships into customers.</span></div></div></div><div className="workflow-preview"><div className="preview-top"><span className="preview-label">Illustrative workflow <span>Example</span></span><span className="preview-dots">•••</span></div><div className="preview-highlight"><div><span className="eyebrow">Example focus queue</span><strong>5 next actions</strong><small>Illustrative records, not live account data</small></div><span className="preview-ring">5</span></div><div className="preview-row"><span className="preview-icon danger-bg">!</span><div><strong>Overdue follow-up</strong><small>Example account · Proposal Sent</small></div><span className="preview-time">1d late</span></div><div className="preview-row"><span className="preview-icon accent-bg"><CircleDot size={15} /></span><div><strong>Confirm buying committee</strong><small>Example account · Qualified</small></div><span className="preview-time">Due Fri</span></div><div className="preview-row"><span className="preview-icon warning-bg"><CircleDot size={15} /></span><div><strong>Review renewal health</strong><small>Example account · Customer</small></div><span className="preview-time">Due Mon</span></div></div></div></section>
      <section id="surface" className="surface-section section-wrap"><div className="section-intro split-intro"><div><span className="eyebrow">The complete surface</span><h2>Useful across the whole relationship—not only the deal.</h2></div><p>Most CRMs stop at a pipeline. CRM360 keeps the surrounding work visible, from first touch to retention and team accountability.</p></div><div className="surface-layout"><div className="surface-map"><div className="surface-map-line" /><div><span className="surface-map-number">01</span><strong>Leads</strong><small>Capture source, owner, stage</small></div><div><span className="surface-map-number">02</span><strong>Customers</strong><small>Context, contacts, activity</small></div><div><span className="surface-map-number">03</span><strong>Tasks</strong><small>Due dates, priority, handoff</small></div><div><span className="surface-map-number">04</span><strong>Insights</strong><small>Pipeline, trends, focus queue</small></div></div><div className="domain-grid">{domainCards.map(({ icon: Icon, label, text }) => <Link className="domain-card" to="/register" key={label} aria-label={`Create a CRM360 account for ${label}`}><span className="domain-icon"><Icon size={19} /></span><div><strong>{label}</strong><p>{text}</p><small className="card-action">Start with CRM360 <ArrowRight size={14} /></small></div></Link>)}</div></div><div className="coverage-row"><span><SearchCheck size={16} /> Search across the workspace</span><span><Route size={16} /> Track a clear next action</span><span><Activity size={16} /> See momentum before it slips</span></div></section>
      <section id="features" className="section-wrap feature-section"><div className="section-intro split-intro"><div><span className="eyebrow">Designed for momentum</span><h2>Less admin. More meaningful follow-through.</h2></div><p>Every surface is there to help someone decide what to do next—not to fill a dashboard with noise.</p></div><div className="feature-grid">{features.map(({ icon: Icon, title, text, action }) => <article className="feature-card" key={title}><span className="feature-icon"><Icon size={21} /></span><h3>{title}</h3><p>{text}</p><Link to="/register">{action} <ArrowRight size={15} /></Link></article>)}</div></section>
      <section id="security" className="trust-section section-wrap"><div className="trust-badge"><ShieldCheck size={24} /></div><div><span className="eyebrow">Trust by default</span><h2>Clear permissions. Honest status. Safe foundations.</h2><p>Role-aware access, validated forms, hashed passwords, and a backend that treats ownership as a permission—not a UI preference.</p></div><Link className="button button-quiet" to="/register">See CRM360 in action <ArrowRight size={16} /></Link></section>
      <section className="final-cta section-wrap"><div className="cta-glow" /><span className="eyebrow">Ready when you are</span><h2>Make the next step<br /><span>the obvious one.</span></h2><Link className="button button-light" to="/register">Launch your workspace <ArrowRight size={17} /></Link></section>
    </main>
    <footer className="landing-footer section-wrap"><Logo /><span>© 2026 CRM360. Every relationship. Every next step.</span><div><a href="#workflow">Workflow</a><Link to="/login">Sign in</Link></div></footer>
  </div>
}
