import { useEffect, useState } from 'react'
import { Check, Mail, Save, Search, ShieldCheck, Users } from 'lucide-react'
import { Link, useSearchParams } from 'react-router'
import { api, request } from '../api'
import { useAuth } from '../auth'
import type { Customer, Lead, Task, User } from '../types'
import { Badge } from '../components/Status'
import { Field } from '../components/FormField'
import { currency, dateLabel } from '../utils'

export function SettingsPage() {
  const { user, refresh } = useAuth(); const [form, setForm] = useState({ name: user?.name || '', phone: user?.phone || '', password: '' }); const [saved, setSaved] = useState(false); const [error, setError] = useState(''); const [saving, setSaving] = useState(false)
  const save = async (event: React.FormEvent) => { event.preventDefault(); setError(''); setSaving(true); try { await request(api.patch('/users/profile', form)); setForm((current) => ({ ...current, password: '' })); setSaved(true); await refresh(); setTimeout(() => setSaved(false), 2500) } catch (e: any) { setError(e?.response?.data?.error || 'Unable to save your profile') } finally { setSaving(false) } }
  return <div className="page-stack"><div className="page-header"><div><span className="eyebrow">Your workspace identity</span><h1>Settings</h1><p className="page-subtitle">Keep your profile current so ownership and follow-through stay clear.</p></div></div><div className="settings-grid"><section className="card settings-card"><div className="card-head"><div><span className="eyebrow">Profile</span><h2>Personal details</h2></div><span className="settings-symbol"><Users size={18} /></span></div><form className="modal-form" onSubmit={save}><Field label="Full name" required><input value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} required /></Field><Field label="Work email"><div className="input-readonly"><Mail size={15} />{user?.email}</div></Field><Field label="Phone"><input value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })} /></Field><Field label="New password"><input type="password" minLength={8} value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} placeholder="Leave blank to keep current" /></Field>{error && <div className="form-error" role="alert">{error}</div>}{saved && <div className="success-inline"><ShieldCheck size={15} /> Profile saved.</div>}<button className="button button-primary" disabled={saving}><Save size={16} /> {saving ? 'Saving...' : 'Save changes'}</button></form></section><section className="card settings-card"><div className="card-head"><div><span className="eyebrow">Access</span><h2>Your role</h2></div></div><div className="role-panel"><span className="role-icon"><ShieldCheck size={20} /></span><div><strong>{user?.role}</strong><p>{user?.role === 'Admin' ? 'Full workspace access, user management, and analytics.' : user?.role === 'Sales Manager' ? 'Team records, assignments, pipeline, and dashboard access.' : 'Assigned records, interactions, tasks, and authorized conversion.'}</p></div></div><p className="settings-note">Permissions are enforced on the backend for every protected resource.</p></section></div></div>
}

export function TeamPage() {
  const [users, setUsers] = useState<User[]>([]); const [error, setError] = useState(''); const load = async () => { try { setUsers((await request<{ users: User[] }>(api.get('/users'))).users) } catch (e: any) { setError(e?.response?.data?.error || 'Unable to load teammates') } }; useEffect(() => { void load() }, []); const changeRole = async (item: User, role: string) => { try { await request(api.patch(`/users/${item.id}/role`, { role })); await load() } catch (e: any) { setError(e?.response?.data?.error || 'Unable to update role') } }
  return <div className="page-stack"><div className="page-header"><div><span className="eyebrow">Workspace access</span><h1>Team</h1><p className="page-subtitle">Make responsibility visible and keep permissions intentional.</p></div></div><div className="form-notice"><ShieldCheck size={15} /> Role changes are audited by the API. Email invitations are not shown until an email provider is configured.</div>{error && <div className="form-error" role="alert">{error}</div>}<div className="card table-card"><div className="table-toolbar"><div className="record-count"><strong>{users.length}</strong> active teammates</div></div><div className="data-table-wrap"><table className="data-table"><thead><tr><th>Person</th><th>Role</th><th>Status</th><th>Access</th></tr></thead><tbody>{users.map((item) => <tr key={item.id}><td><div className="person-cell"><span className="avatar avatar-table">{item.name.slice(0, 1)}</span><div><strong>{item.name}</strong><small>{item.email}</small></div></div></td><td><select className="inline-select" value={item.role} onChange={(e) => void changeRole(item, e.target.value)} aria-label={`Change role for ${item.name}`}><option>Admin</option><option>Sales Manager</option><option>Sales Executive</option></select></td><td><Badge tone="success">Active</Badge></td><td><span className="muted">Backend-enforced RBAC</span></td></tr>)}</tbody></table></div></div></div>
}

export function SearchPage() {
  const [params] = useSearchParams(); const query = params.get('q') || ''; const [results, setResults] = useState<{ customers: Customer[]; leads: Lead[]; tasks: Task[] }>({ customers: [], leads: [], tasks: [] }); const [error, setError] = useState(''); const [loading, setLoading] = useState(false)
  useEffect(() => { if (!query) return; setLoading(true); Promise.all([request<{ items: Customer[] }>(api.get('/customers', { params: { search: query, limit: 10 } })), request<{ items: Lead[] }>(api.get('/leads', { params: { search: query, limit: 10 } })), request<{ items: Task[] }>(api.get('/tasks', { params: { limit: 50 } }))]).then(([customers, leads, tasks]) => setResults({ customers: customers.items, leads: leads.items, tasks: tasks.items.filter((task) => task.title.toLowerCase().includes(query.toLowerCase())) })).catch((e: any) => setError(e?.response?.data?.error || 'Unable to search this workspace')).finally(() => setLoading(false)) }, [query])
  if (!query) return <div className="empty-state card"><span className="empty-icon"><Search size={22} /></span><h3>Search the workspace</h3><p>Use the search field above to find customers, leads, and tasks by name or company.</p></div>
  return <div className="page-stack"><div className="page-header"><div><span className="eyebrow">Global search</span><h1>Results for “{query}”</h1><p className="page-subtitle">Search across your relationship records and next actions.</p></div></div>{error && <div className="form-error" role="alert">{error}</div>}{loading ? <div className="page-loader">Searching the workspace...</div> : <div className="search-results-grid"><SearchResult title="Customers" count={results.customers.length}>{results.customers.map((item) => <Link key={item._id} to="/app/customers"><span className="avatar avatar-tiny">{item.name.slice(0, 1)}</span><span><strong>{item.name}</strong><small>{item.company}</small></span></Link>)}</SearchResult><SearchResult title="Leads" count={results.leads.length}>{results.leads.map((item) => <Link key={item._id} to="/app/leads"><span className="avatar avatar-tiny avatar-violet">{item.name.slice(0, 1)}</span><span><strong>{item.name}</strong><small>{item.company} · {currency(item.estimatedValue)}</small></span></Link>)}</SearchResult><SearchResult title="Tasks" count={results.tasks.length}>{results.tasks.map((item) => <Link key={item._id} to="/app/tasks"><span className="avatar avatar-tiny avatar-amber"><Check size={12} /></span><span><strong>{item.title}</strong><small>Due {dateLabel(item.dueDate)}</small></span></Link>)}</SearchResult></div>}</div>
}

function SearchResult({ title, count, children }: { title: string; count: number; children: React.ReactNode }) { return <section className="card search-result-card"><div className="card-head"><h2>{title}</h2><Badge>{count}</Badge></div>{count ? <div className="search-result-list">{children}</div> : <p className="muted">No matches.</p>}</section> }
